### ISSUE TITLE
Errors in generated kotlin

### ISSUE THREAD

**Issue by ghost** [leveretka/grpc-death-star#4]
Hi, I started using your plugins few minutes ago and I already have some issues while generating my kotlin code, I tried to check different things in my project to see if I was not missing any dependencies of some sort but it looks like I'm not.

Here are the errors I get : 

```
e: NewsServiceImplBase.kt: (32, 29): Unresolved reference: getReceiveNewsMethod
e: NewsServiceImplBase.kt: (50, 17): Unresolved reference: getReceiveNewsMethod
e: NewsServiceImplBase.kt: (51, 29): Type inference failed: Not enough information to infer parameter ReqT in fun <ReqT : Any!, RespT : Any!> asyncUnaryCall(p0: ServerCalls.UnaryMethod<ReqT!, RespT!>!): ServerCallHandler<ReqT!, RespT!>!
Please specify it explicitly.

e: NewsServiceImplBase.kt: (52, 21): Type inference failed: Not enough information to infer parameter Req in constructor MethodHandlers<Req, Resp>(methodId: Int)
Please specify it explicitly.
````

(I removed a part of the path in the error for some confidential reasons).
I can give the code lines related to the error if needed.

**Comment by Godin** [comment]
> your plugins

This repository doesn't provide any plugins.

**Comment by ghost** [comment]
Oh... I wrote the issue in the wrong repository.
